name: level_up
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  supabase_flutter: ^2.5.6
  flutter_dotenv: ^5.1.0
  fluent_ui: ^4.8.7
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  teledart: ^0.6.1
  http: ^1.2.1
  percent_indicator: ^4.2.3
  dropdown_button2: ^2.3.9
  flutter_image_stack: ^0.0.7
  expandable: ^5.0.1
  intl: ^0.19.0
  provider: ^6.1.2
  rxdart: ^0.27.7
  path_provider: ^2.1.3
  flutter_local_notifications: ^12.0.0
  timezone: ^0.9.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_levelup.png" 

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo_levelup.png
    - assets/dev.png
    # ALERT
    - assets/alerts/no-internet.png
    - assets/alerts/onprogress.png

    # NAVIGATION BAR ACTIVE
    - assets/navigation/active/dashboard.svg
    - assets/navigation/active/okr.svg
    - assets/navigation/active/presensi.svg
    - assets/navigation/active/profile.svg
    # NAVIGATION BAR INACTIVE
    - assets/navigation/inactive/dashboard.svg
    - assets/navigation/inactive/okr.svg
    - assets/navigation/inactive/presensi.svg
    - assets/navigation/inactive/profile.svg

    # LOGIN
    - assets/login/background-levelup.png
    - assets/login/google.png

    # PRESENSI
    - assets/presensi/condition.png

    # OKR 
    - assets/okr/profile.png
    - assets/okr/pp.png
    - assets/okr/success.png
    - assets/okr/failed.png
    - assets/okr/goal.png
    - assets/okr/profile-1.png
    - assets/okr/profile-2.png
    - assets/okr/profile-3.png
    - assets/okr/profile-4.png

    # PROFILE
    - assets/profile/instagram.svg
    - assets/profile/linkedin.svg
